- name: Labeler
  uses: actions/labeler@v4.0.2
# Add 'label1' to any changes within 'example' folder or any subfolders

Project1:
- Project1/js.html

# Add 'label2' to any file changes within 'example2' folder
Project2: Project2/index.html


