name: "🐛 Bug"
description: Report an issue to help improve the project.
labels: ["Nishitbaria"]

body:
  - type: dropdown
    id: issueType
    attributes:
      label: Issue Type
      description: "Thank you for reporting a bug!"
      options:
        - Frontend
        - Backend
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false

{% if inputs.issueType == "Frontend" %}
  - type: markdown
    attributes:
      value: |
        **Frontend Label**
{% elif inputs.issueType == "Backend" %}
  - type: markdown
    attributes:
      value: |
        **Backend Label**
{% endif %}

- type: markdown
  attributes:
    value: |
      You can also join our Discord community [here](http://discord.eddiehub.org)
      Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)
