---
name: "\U0001F41B Bug Report"
about: Report a bug to help us improve

---

## Issue Type
<!-- Select the appropriate issue type by placing an "x" in the square brackets -->
- [ ] Frontend
- [ ] Backend

## Description
<!-- Provide a detailed description of the issue -->
<!-- Include what you tried and what didn't work -->

## Screenshots
<!-- Add screenshots if applicable -->

## Additional Information
<!-- Add any additional information that might be helpful -->

<!-- Feel free to add any relevant labels or assignees -->
<!-- You can also join our Discord community [here](http://discord.eddiehub.org) -->
<!-- Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity) -->
