name: "🐛 Bug"
about: Report an issue to help improve the project.

on:
  issues:
    types:
      - opened

jobs:
  createIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: ${{ github.event.issue.title }}
          body: |
            **Issue Type**: ${{ github.event.issue.body }}
            
            **Description**:
            ${{ github.event.issue.body }}
            
            **Screenshots**:
            ${{ github.event.issue.body }}
            
            **Additional Information**:
            ${{ github.event.issue.body }}

          labels: "Nishitbaria"
