name: "Label Workflow"
on:
  issues:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Frontend
        if: ${{ contains(github.event.issue.body, 'Frontend') }}
        run: echo "::set-output name=frontend::true"
  
      - name: Check for Backend
        if: ${{ contains(github.event.issue.body, 'Backend') }}
        run: echo "::set-output name=backend::true"

      - name: Add Labels
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            if (process.env.frontend) {
              github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['frontend']
              });
            }
            if (process.env.backend) {
              github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['backend']
              });
            }
