name: Assign Frontend Label

on:
  issues:
    types: [opened]

jobs:
  assignLabel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assign Frontend Label
        if: ${{ github.event.issue.body.issueType == 'Frontend' }}
        uses: peter-evans/add-labels@v3
        with:
          labels: Frontend
          issue-number: ${{ github.event.issue.number }}
