name: Issue Assignment

on:
  push:
    branches:
      - main

jobs:
  issue_assignment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GitHub API authentication
        uses: actions/setup-github@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract mentioned user from commit message
        id: extract_user
        run: |
          USERNAME=$(echo ${{ github.event.commits[0].message }} | grep -o -P '(?<=Hey @)\w+(?=\s,)')
          echo ::set-output name=USERNAME::$USERNAME

      - name: Check if mentioned user is different from commit author
        run: |
          COMMIT_AUTHOR=$(git show -s --format='%an' ${{ github.event.commits[0].sha }})
          if [ "$COMMIT_AUTHOR" = "$USERNAME" ]; then
            echo "You cannot assign an issue to yourself"
            exit 1
          fi

      - name: Assign issue to mentioned user
        run: |
          gh issue assign --repo ${{ github.repository }} $USERNAME ${{ github.event.commits[0].issue.number }}
          echo "Issue assigned to $USERNAME"

      - name: Reply to commit with assignment message
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = `Hey @${context.payload.commits[0].author.username}, You can start working on this issue. Please follow the contribution guidelines mentioned in the repository: [CONTRIBUTING.md](${{ github.repository }}/blob/main/CONTRIBUTING.md)`
            github.rest.issues.createComment({
              issue_number: context.payload.commits[0].issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })
